session_name: ajth-in-personal-website
start_directory: ./

before_script: git pull --rebase

windows:
  - window_name: workplace
    layout: tiled
    panes:
      - pnpm run serve
      - lazygit
      - opencode .
      -

  - window_name: editor
    focus: true
    panes:
      - shell_command:
          - nvim .
        focus: true
